package main

import (
	"log"
	"logIn/database"
	"logIn/handlers"
	"net/http"
	 _"logIn/docs"                          // generated by swag
    httpSwagger "github.com/swaggo/http-swagger"
)
// @title           Login App API
// @version         1.0
// @description     A simple authentication API with register and login endpoints
// @host            localhost:8080
// @BasePath        /
func main() {

	db, err := database.ConnectDB()
	if err != nil {
		log.Fatal("Could not connect to database: ", err)
	}

	http.HandleFunc("/register", handlers.RegisterHandler(db))
	http.HandleFunc("/login", handlers.LoginHandler(db))
	http.HandleFunc("/swagger/", httpSwagger.WrapHandler)

	log.Println("Server is running on port :8080")
	log.Println("http://localhost:8080/login")
	log.Println("http://localhost:8080/register")
	log.Println("http://localhost:8080/swagger/")

	log.Fatal(http.ListenAndServe(":8080", nil))
}